### PR TITLE
fix: Convert package to ESM

### PR DESCRIPTION
**Pull request by UziTech**

### CODE REVIEW

**Comment by travi** [comment]
we'll need to coordinate this with also converting the core package and the official packages that it depends on. @gr2m has started that effort in https://github.com/semantic-release/github/pull/419. there may be some details of that conversion that are worth being consistent with or giving feedback about.

instead of opening this PR against master, it would be best to create a `beta` branch and open the PR against that branch so that we can make a pre-release of the changes before promoting to `latest`

**Comment by travi** [comment]
it looks like the `beta` branch might be an old existing branch? probably best to clean up that old branch and create a new one

**Comment by UziTech** [comment]
It looks like I am unable to delete the beta branch since it is protected.

**Comment by travi** [comment]
> unable to delete the beta branch since it is protected.

ah, i think that was configured before github allowed deleting protected branches. i've updated the branch protection to allow deletions now. could you confirm that it works for you now?

**Pull request closed without merging**
