### PR TITLE
feat(node-version): raised the minimum required version to v14.17 

### PR DESCRIPTION
**Pull request by UziTech**

### CODE REVIEW

**Comment by travi** [comment]
thank you for the contribution. however, since semantic-release v18 defines an engines range that is more restricted than the range currently defined for this package, it does not satisfy the contract of this package without changing the engines range defined here, which is a breaking change. 

if you would like to help us get this package updated to be compatible with v18 of semantic-release, this would be a good example to follow: https://github.com/semantic-release/github/pull/397/files

**Comment by UziTech** [comment]
> since semantic-release v18 defines an engines range that is more restricted than the range currently defined for this package, it does not satisfy the contract of this package without changing the engines range defined here, which is a breaking change.

That is not true. This change doesn't force people to use semantic-release v18. it only allows them to use it. People can still use older versions that allow older versions of node that this package allows.

**Comment by travi** [comment]
> That is not true. This change doesn't force people to use semantic-release v18. it only allows them to use it. People can still use older versions that allow older versions of node that this package allows.

i understand your point, but the peer dependency definition communicates the versions of the dependency that _are compatible_ with the current package. because the engines range for v18 of semantic-release is not fully compatible with the engines range for the current version of this package, defining it as a valid peer would be inaccurate. 

the way we intend to provide compatibility for this package is to adjust the engines range of this package as a breaking change. if you would like to help us accomplish that sooner, a PR with the changes mentioned above would be welcomed.

**Comment by UziTech** [comment]
I added the changes in https://github.com/semantic-release/github/pull/397/files

**Review by travi — APPROVED** [review]
thanks so much for helping us move the update forward for this plugin! really appreciate the help!

**Comment by travi** [comment]
it looks like CI is failing with these changes for some reason. it isnt obvious to me at first glance if this would truly be related to the changes or some fluke with github actions.

would you mind taking a look to see if the error is something that you might have some insight into?

**Comment by UziTech** [comment]
I was able to reproduce this locally when running `npm ci`. It seems like the issue was because the lockfile version was 2 but npm that is included with node v14.17 expects version 1 lockfile. It should pass now.

**Comment by travi** [comment]
great! thanks for digging in and sorting that out. it looks like that did get us past that step, but now we have an ls-engines failure. due to https://github.com/ljharb/ls-engines/pull/23, i'm unsure if the failure is legitimate or due to the bug. i will try to investigate further a bit later, but this might need that fix to land.

**Comment by travi** [comment]
looks like the problem is actually that the node version is set back to v12 after `actions/setup-node@v2` by `UziTech/action-setup-atom@v1`. seeing the name on that action, i have a feeling that you might be better prepared to adjust that config than i am. would you mind sorting that out so that the matrix version is used as expected?

**Comment by travi** [comment]
that got the build passing. thanks for investigating @UziTech! one question before we merge though: do we still need the setup-node action, or should setup-atom simply be used instead?

**Comment by UziTech** [comment]
Ya the setup-node action installs the version of node specified. Atom is bundled with node v12 which is why it was overriding v14 when installed after.

**Comment by travi** [comment]
@UziTech i've been meaning for follow up after your contributions to help us out with the recent updates. we really appreciated the assistance. since we have no current maintainers that use the apm ecosystem, we are somewhat limping the apm projects along to keep them maintained. 

would you be interested in helping us maintain the apm projects more officially?

**Comment by UziTech** [comment]
Ya I would love to help out :smile::+1:

**Comment by travi** [comment]
great! i've invited you to a new apm team that will grant you write access this repo and the apm-config repo. these two projects don't require a lot of maintenance, but we appreciate the help!

**Pull request merged**
